/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BecomeATeacherRouteImport } from './routes/become-a-teacher'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FindTeacherRouteImport } from './routes/find-teacher'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPostRequirementRouteImport } from './routes/_authenticated/post-requirement'
import { Route as TeachersIdRouteImport } from './routes/teachers.$id'
import { Route as ApiPublicTeacherPhotoSplatRouteImport } from './routes/api/public/teacher-photo/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeATeacherRoute = BecomeATeacherRouteImport.update({
  id: '/become-a-teacher',
  path: '/become-a-teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FindTeacherRoute = FindTeacherRouteImport.update({
  id: '/find-teacher',
  path: '/find-teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostRequirementRoute =
  AuthenticatedPostRequirementRouteImport.update({
    id: '/post-requirement',
    path: '/post-requirement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TeachersIdRoute = TeachersIdRouteImport.update({
  id: '/teachers/$id',
  path: '/teachers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTeacherPhotoSplatRoute =
  ApiPublicTeacherPhotoSplatRouteImport.update({
    id: '/api/public/teacher-photo/$',
    path: '/api/public/teacher-photo/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-teacher': typeof BecomeATeacherRoute
  '/contact': typeof ContactRoute
  '/find-teacher': typeof FindTeacherRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/post-requirement': typeof AuthenticatedPostRequirementRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/api/public/teacher-photo/$': typeof ApiPublicTeacherPhotoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-teacher': typeof BecomeATeacherRoute
  '/contact': typeof ContactRoute
  '/find-teacher': typeof FindTeacherRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/post-requirement': typeof AuthenticatedPostRequirementRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/api/public/teacher-photo/$': typeof ApiPublicTeacherPhotoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/become-a-teacher': typeof BecomeATeacherRoute
  '/contact': typeof ContactRoute
  '/find-teacher': typeof FindTeacherRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/post-requirement': typeof AuthenticatedPostRequirementRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/api/public/teacher-photo/$': typeof ApiPublicTeacherPhotoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-a-teacher'
    | '/contact'
    | '/find-teacher'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/dashboard'
    | '/post-requirement'
    | '/teachers/$id'
    | '/api/public/teacher-photo/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-a-teacher'
    | '/contact'
    | '/find-teacher'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/dashboard'
    | '/post-requirement'
    | '/teachers/$id'
    | '/api/public/teacher-photo/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/become-a-teacher'
    | '/contact'
    | '/find-teacher'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/post-requirement'
    | '/teachers/$id'
    | '/api/public/teacher-photo/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BecomeATeacherRoute: typeof BecomeATeacherRoute
  ContactRoute: typeof ContactRoute
  FindTeacherRoute: typeof FindTeacherRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  TeachersIdRoute: typeof TeachersIdRoute
  ApiPublicTeacherPhotoSplatRoute: typeof ApiPublicTeacherPhotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-teacher': {
      id: '/become-a-teacher'
      path: '/become-a-teacher'
      fullPath: '/become-a-teacher'
      preLoaderRoute: typeof BecomeATeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-teacher': {
      id: '/find-teacher'
      path: '/find-teacher'
      fullPath: '/find-teacher'
      preLoaderRoute: typeof FindTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-requirement': {
      id: '/_authenticated/post-requirement'
      path: '/post-requirement'
      fullPath: '/post-requirement'
      preLoaderRoute: typeof AuthenticatedPostRequirementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/teachers/$id': {
      id: '/teachers/$id'
      path: '/teachers/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof TeachersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/teacher-photo/$': {
      id: '/api/public/teacher-photo/$'
      path: '/api/public/teacher-photo/$'
      fullPath: '/api/public/teacher-photo/$'
      preLoaderRoute: typeof ApiPublicTeacherPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPostRequirementRoute: typeof AuthenticatedPostRequirementRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPostRequirementRoute: AuthenticatedPostRequirementRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BecomeATeacherRoute: BecomeATeacherRoute,
  ContactRoute: ContactRoute,
  FindTeacherRoute: FindTeacherRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  TeachersIdRoute: TeachersIdRoute,
  ApiPublicTeacherPhotoSplatRoute: ApiPublicTeacherPhotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
